name: "test-actions"

on:
    pull_request:
        branches: [ extra ]

jobs:    
    test_pull_request:
        runs-on: ubuntu-latest
        steps:
            - run: pip install pytest
            - run: pytest
            - run: python try_actions.py
