name: "test-actions"

on:
    pull_request:
        branches: [ main ]

jobs:    
    test_pull_request:
        runs-on: ubuntu-latest

        defaults: 
            run:
                working-directory: ./src/

        strategy:
            fail-fast: false
            matrix:
                python-version: [3.8, 3.9]

        env:
            MODE: "dev"

        steps:
            
            - name: Checkout code i.e. setup the environment
              uses: actions/checkout@v2
              timeout-minutes: 0.1

            - name: Set up Python  
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r ../requirements.txt
                    # timeout-minutes: 300

            - run: python -m pytest
            # --import-mode=append tests/
            - run: python ./try_actions.py
