name: "test-actions"

on:
    pull_request:
        branches: [ main ]

jobs:    
    test_pull_request:
        runs-on: ubuntu-latest
        steps:
            - run: pip install pytest
            - run: python -m pytest --import-mode=append tests/
            - run: python try_actions.py
